[project]
name = "gitlab-mistral-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32",
    "pydantic-settings>=2.2",
    "filelock>=3.13",
    "apscheduler>=3.10",
]
